spring:
  application:
    name: student-info-service
#  config:
#    import: "optional:configserver:"
  profiles:
    active: local
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: xe
    password: password
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
  graphql:
    graphiql:
      enabled: true
    
server:
  port: 9002
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${eureka.instance.hostname}:${server.port}