spring:
  application:
    name: student-info-service
  profiles:
    active: local
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: xe
    password: password
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
  graphql:
    graphiql:
      enabled: true
  zipkin:
    message-timeout: 10000
    check-timeout: 10000
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${eureka.instance.hostname}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    status-page-url-path: /actuator/health
    
management:
  endpoints:
    web:
      exposure:
        include: '*'