spring:
  application:
    name: student-info-service
  config:
    import: "optional:configserver:"
  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521:xe
    username: likhith
    password: likhith
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
    
server:
  port: 9001
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: "http://localhost:8761/eureka"
  instance:
    hostname: ${spring.application.name}
    instance-id: ${spring.application.name}:${server.port}